typo fix and more info about elf2uf2
rp-rs/rp2040-project-template pull request #13
Opened 2021-12-10 09:42 UTC by Pavan-Parker

2021-12-10 13:23 UTC, jonathanpallant requested changes

2021-12-10 13:23 UTC, jonathanpallant commented on .cargo/config.toml
> +# elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode, which required you to install corresponding package by executing "$ cargo install elf2uf2-rs"
I don't think this comment is needed - both probe-run and elf2usb2-rs require installation.

2021-12-10 13:23 UTC, jonathanpallant commented on .cargo/config.toml
> +# runner = "elf2uf2-rs -d"
But this is a good spot. Oops!

2021-12-10 13:27 UTC, jonathanpallant commented on .cargo/config.toml
> +# elf2uf2-rs loads firmware over USB when the rp2040 is in boot mode, which required you to install corresponding package by executing "$ cargo install elf2uf2-rs"
I've added this to the README in #14

2021-12-21 03:05 UTC, 9names commented
These changes were also in #18 which had a few other fixes, so I've merged that one instead.
Thanks for the PR @Pavan-Parker

2021-12-21 03:05 UTC, closed without merging