Rename license file to standardised name
rp-rs/rp2040-project-template pull request #89
Opened 2024-11-12 19:58 UTC by moritztim

Saving the license in a file that is named `MIT` prevents tools like VSCode and GitHub (see [GitHub docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)) as well as users to recognize it as a license file at a glance. The convention is to name it `LICENSE`.

2024-11-12 20:02 UTC, moritztim commented
I just realised that this is licensed under both the MIT _and_ the Apache 2.0 license... I guess this complicates things a bit. Maybe there should be a third file `LICENSE` with the license that the actual code here is under, as opposed to the possible licenses that could be chosen for any projects using this template.

2024-11-12 20:12 UTC, moritztim commented
According to the [SPDX specification on composite license expressions](https://spdx.github.io/spdx-spec/v3.0.1/annexes/spdx-license-expressions/#composite-license-expressions) you just have to put an "OR" keyword between the license options.

2024-11-12 20:14 UTC, moritztim commented
The "License" tab shows up with this change. Unfortunately, it doesn't show both licenses in full.
![The "License" tab on my fork's GitHub page](https://github.com/user-attachments/assets/923684bb-258e-4711-aeed-2985f8322d58)

2024-11-12 20:24 UTC, moritztim commented
This almost works. Unfortunately GitHub doesn't recognize the apache license because it has another dot in its name.
!["License" tab](https://github.com/user-attachments/assets/1be4e774-cbd4-4527-a216-745d6df48e6e)
!["MIT License" tab](https://github.com/user-attachments/assets/59f26277-61f3-4f2e-91fc-7c740f3c3e2d)

2024-11-12 20:40 UTC, moritztim commented
Now it's getting correctly displayed by GitHub.
![License tabs on my fork](https://github.com/user-attachments/assets/27b07c70-3a6c-4abf-8d8e-dc33be33e66d)
You might not want to have a third `LICENSE` file with the standardized expression, since it might be confusing to have three files. 
![Sidebar](https://github.com/user-attachments/assets/2ac7d7cc-85d6-471b-943e-b2f6161e7771)

2024-11-12 21:24 UTC, jannic commented
The README.md refers to these files as well. ("See MIT or APACHE2.0 for more information on each specific licence.")
That should probably be updated to point to the renamed files.

2024-11-12 21:40 UTC, moritztim commented
Right, I'll do that

2024-11-12 21:45 UTC, 9names reviewed
FYI our main repo uses the same licences and GitHub detects them correctly.
We should have it done consistently.
https://github.com/rp-rs/rp-hal

2024-11-12 21:49 UTC, moritztim commented
> FYI our main repo uses the same licences and GitHub detects them correctly. We should have it done consistently. [rp-rs/rp-hal](https://github.com/rp-rs/rp-hal)

Yeah, since the readme mentions the dual license with a proper `OR` clause, I think the `LICENSE` file might not be needed. I'll remove it and the reference to it if you want.

2024-11-13 16:34 UTC, moritztim commented
@9names I've implemented your latest request, would you mind just giving your final verdict so I can start using my fork as a template with your blessings (on the relevant changes here)?

2025-04-05 18:10 UTC, ithinuel commented
Yes please.

2025-04-06 05:07 UTC, moritztim commented
It's been a while, can you remind me what I need to remove exactly?

2025-05-03 06:09 UTC, 9names commented
@moritztim you need to remove the thing you said you would remove, exactly 1 post above ithinuel's reply:

> I think the LICENSE file might not be needed.

which is the only file you added in this PR, the other changes were 2 file renames and updating the readme to point to those files.

2025-05-04 01:39 UTC, 9names requested changes

2025-05-04 01:39 UTC, 9names commented on README.md
> +The contents of this repository are dual-licensed under the _[MIT](LICENSE-MIT) OR [Apache-2.0](LICENSE-APACHE_2.0)_ License. That means you can chose either the MIT licence or the
This first link to Apache 2.0 license has a typo (_ instead of -)
Did you test it?

2025-05-04 06:20 UTC, moritztim commented
Fixed and tested on GitHub.

2025-05-04 06:21 UTC, 9names approved these changes

2025-05-04 06:22 UTC, merged